### ISSUE TITLE
Monkey patching asset pipeline helpers in RoR 

### ISSUE THREAD

**Issue by andreicek** [infinum/webpack-rails-manifest-plugin#2]
In the readme there is already support for adding a new helper but it would be much better if there was also a way to monkey patch other helpers that will stop working.

**Comment by andreicek** [comment]
One more thing: it should be added that all the files **have to be required** in the JavaScript in order for webpack to process them.

Eg. `files.js`

``` JavaScript
require('images/file1.jpg');
require('images/file2.jpg');
require('images/file3.jpg');
```

And then in `application.js` (your entrypoint)

``` JavaScript
require('file');
```

This note can be placed under a new chapter of README: eg. Example. If needed also modify the `example/` folder to mirror the usage.

And then you can use it in your HTML

``` HTML
<img src="#{webpack_asset_url('images/file1.jpg')}" alt="logo" />
```

**Comment by gabskoro** [comment]
This is done at PRs #13 and #14
